### ISSUE TITLE
ERROR ReferenceError: Slider is not defined at SliderComponent

### ISSUE THREAD

**Issue by Danyx1980** [moritzvieli/ngx-bootstrap-slider#10]
I've followed the installation guide by adding both the bootstral slider js and css to the angular.json file, yet I keep getting this error.

**Comment by errezz** [comment]
I got the same problem...

**Comment by tobo37** [comment]
Same problem but not with ng serve / build --prod ([prod-webside](https://covid-o-mat.de/)). Only by testing.
`ReferenceError: Slider is not defined
            at <Jasmine>
            at SliderComponent.ngOnInit (http://localhost:9876/_karma_webpack_/node_modules/ngx-bootstrap-slider/__ivy_ngcc__/fesm2015/ngx-bootstrap-slider.js:174:1)
            at callHook (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:4686:1)
            at callHooks (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:4650:1)
            at executeInitAndCheckHooks (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:4591:1)
            at selectIndexInternal (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9621:1)
            at ɵɵadvance (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9582:1)
            at HomeComponent_Template (ng:///HomeComponent.js:237:9)
            at executeTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11949:1)
            at refreshView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11796:1)
            at refreshComponent (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13229:1)`

Angular 9.1.0,
ngx-bootstrap-slider": "1.8.0",

code:
```
<mv-slider [(value)]="myvalue" [min]="1" [max]="20" [enabled]="true"
      (change)="myfunction($event)" style="width: 100%;">
      </mv-slider>
```

**Comment by simonvollmer** [comment]
I am having the same issue. Can this please be looked at.

**Comment by yudarik** [comment]
Having the same issue with ngx-bootstrap-slider": "1.9.0" and NG 9.1.12

**Comment by RaschidJFR** [comment]
Workaround:

1. install bootstrap-slider: `$ npm i bootstrap-slider`

2. Add this somewhere in your code before using `ngx-bootstrap-slider`

    ```
    import Slider from 'bootstrap-slider';
    (window as any).Slider = Slider;
    ```
